services:
  - type: web
    name: gacha-countdown
    runtime: node
    plan: free
    branch: main
    startCommand: bun run production
    buildCommand: bun ci && bun run build
    envVars:
      - key: NITRO_PRESET
        value: render_com
