services:
  - type: web
    name: gacha-countdown
    runtime: node
    branch: main
    startCommand: bun production
    buildCommand: bun install && bun build
    envVars:
      - key: NITRO_PRESET
        value: render_com
